// Mocks generated by Mockito 5.4.5 from annotations
// in sickness_manager/test/mocks/data_sources.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sickness_manager/app/core/common/enums.dart' as _i6;
import 'package:sickness_manager/app/core/common/types/result.dart' as _i2;
import 'package:sickness_manager/app/domain/data_sources/absences_data_source.dart'
    as _i3;
import 'package:sickness_manager/app/domain/data_sources/auth_data_source.dart'
    as _i8;
import 'package:sickness_manager/app/domain/models/absence.dart' as _i5;
import 'package:sickness_manager/app/domain/models/member.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResult_0<T> extends _i1.SmartFake implements _i2.Result<T> {
  _FakeResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AbsencesDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAbsencesDataSource extends _i1.Mock
    implements _i3.AbsencesDataSource {
  @override
  _i4.Future<_i2.Result<List<_i5.Absence?>>> getAbsences({
    int? offset = 0,
    int? limit = 10,
    _i6.AbsenceType? type,
    _i6.AbsenceStatus? status,
    int? memberId,
    int? crewId,
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAbsences, [], {
              #offset: offset,
              #limit: limit,
              #type: type,
              #status: status,
              #memberId: memberId,
              #crewId: crewId,
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue: _i4.Future<_i2.Result<List<_i5.Absence?>>>.value(
              _FakeResult_0<List<_i5.Absence?>>(
                this,
                Invocation.method(#getAbsences, [], {
                  #offset: offset,
                  #limit: limit,
                  #type: type,
                  #status: status,
                  #memberId: memberId,
                  #crewId: crewId,
                  #startDate: startDate,
                  #endDate: endDate,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.Result<List<_i5.Absence?>>>.value(
                  _FakeResult_0<List<_i5.Absence?>>(
                    this,
                    Invocation.method(#getAbsences, [], {
                      #offset: offset,
                      #limit: limit,
                      #type: type,
                      #status: status,
                      #memberId: memberId,
                      #crewId: crewId,
                      #startDate: startDate,
                      #endDate: endDate,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Result<List<_i5.Absence?>>>);

  @override
  _i4.Future<int> getAbsencesCount() =>
      (super.noSuchMethod(
            Invocation.method(#getAbsencesCount, []),
            returnValue: _i4.Future<int>.value(0),
            returnValueForMissingStub: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<_i2.Result<List<_i7.Member?>>> getMembers() =>
      (super.noSuchMethod(
            Invocation.method(#getMembers, []),
            returnValue: _i4.Future<_i2.Result<List<_i7.Member?>>>.value(
              _FakeResult_0<List<_i7.Member?>>(
                this,
                Invocation.method(#getMembers, []),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.Result<List<_i7.Member?>>>.value(
                  _FakeResult_0<List<_i7.Member?>>(
                    this,
                    Invocation.method(#getMembers, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Result<List<_i7.Member?>>>);
}

/// A class which mocks [AuthDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthDataSource extends _i1.Mock implements _i8.AuthDataSource {
  @override
  _i4.Future<_i2.Result<String?>> login({
    required String? username,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {
              #username: username,
              #password: password,
            }),
            returnValue: _i4.Future<_i2.Result<String?>>.value(
              _FakeResult_0<String?>(
                this,
                Invocation.method(#login, [], {
                  #username: username,
                  #password: password,
                }),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.Result<String?>>.value(
              _FakeResult_0<String?>(
                this,
                Invocation.method(#login, [], {
                  #username: username,
                  #password: password,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Result<String?>>);
}
