// Mocks generated by Mockito 5.4.5 from annotations
// in sickness_manager/test/mocks/outputs.mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes, duplicate_ignore
import 'package:mockito/mockito.dart' as _i1;
import 'package:sickness_manager/app/features/absences/view_model/absences_output.dart'
    as _i2;
import 'package:sickness_manager/app/features/login/view_model/login_output.dart'
    as _i4;
import 'package:sickness_manager/app/features/startup/view_model/startup_output.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AbsencesOutput].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: must_be_immutable
class MockAbsencesOutput extends _i1.Mock implements _i2.AbsencesOutput {
  @override
  void goToLogin() => super.noSuchMethod(
    Invocation.method(#goToLogin, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [StartupOutput].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: must_be_immutable
class MockStartupOutput extends _i1.Mock implements _i3.StartupOutput {
  @override
  void goToLogin() => super.noSuchMethod(
    Invocation.method(#goToLogin, []),
    returnValueForMissingStub: null,
  );

  @override
  void goToAbsences() => super.noSuchMethod(
    Invocation.method(#goToAbsences, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [LoginOutput].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: must_be_immutable
class MockLoginOutput extends _i1.Mock implements _i4.LoginOutput {
  @override
  void goToAbsences() => super.noSuchMethod(
    Invocation.method(#goToAbsences, []),
    returnValueForMissingStub: null,
  );
}
