name: sickness_manager
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  equatable: ^2.0.7
  json_serializable: ^6.9.4
  json_annotation: ^4.9.0
  go_router: ^14.8.1
  dio: ^5.8.0+1
  cupertino_icons: ^1.0.8
  shimmer: ^3.0.0
  loading_indicator: ^3.1.1
  font_awesome_flutter: ^10.8.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  test: ^1.25.15
  mockito: ^5.4.5
  analyzer: ^7.3.0


flutter:

  uses-material-design: true

  assets:
    - assets/


